<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="pandoc" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
  <meta name="author" content="Tianyi He" />
  <meta name="dcterms.date" content="2024-07-27" />
  <title>STA 369 Class 02 @ HD &amp; Lecture 03 @ UOA</title>

<style type="text/css" charset="utf-8">
/* cleanrmd basic defaults */
body {
  /* at least one is usually overridden by the theme, but these ensure the
  body doesn't go all the way up to the screen edge */
  margin: 0.5em auto;
  padding: 0.5em;
  max-width: 48em;
}
code, code * { font-family: inherit; }

@media only screen and (max-width: 768px) {
  body { max-width: 100%; }
}
</style>

  
  <link href="class02_modified_files/cleanrmd-0.1.1.9000/theme-picker.css" rel="stylesheet" />
  <script src="class02_modified_files/cleanrmd-0.1.1.9000/theme-picker.js"></script>
  <script id="theme-picker-themes" type="application/json">[{"name":"almond","src":"almond/almond.css"},{"name":"awsm.css","src":"awsm.css/awsm.css"},{"name":"axist","src":"axist/axist.css"},{"name":"bamboo","src":"bamboo/bamboo.css"},{"name":"bullframe","src":"bullframe/bullframe.css"},{"name":"holiday","src":"holiday/holiday.css"},{"name":"kacit","src":"kacit/kacit.css"},{"name":"latex.css","src":"latex.css/latex.css"},{"name":"markdown-splendor","src":"markdown-splendor/markdown-splendor.css"},{"name":"markdown-retro","src":"markdown-retro/markdown-retro.css"},{"name":"markdown-air","src":"markdown-air/markdown-air.css"},{"name":"markdown-modest","src":"markdown-modest/markdown-modest.css"},{"name":"marx","src":"marx/marx.css"},{"name":"minicss","src":"minicss/minicss.css"},{"name":"new.css","src":"new.css/new.css"},{"name":"no-class","src":"no-class/no-class.css"},{"name":"picocss","src":"picocss/pico.css"},{"name":"sakura","src":"sakura/sakura.css"},{"name":"sakura-vader","src":"sakura-vader/sakura-vader.css"},{"name":"semantic","src":"semantic/semantic.css"},{"name":"simplecss","src":"simplecss/simple.css"},{"name":"style-sans","src":"style-sans/style-sans.css"},{"name":"style-serif","src":"style-serif/style-serif.css"},{"name":"stylize","src":"stylize/stylize.css"},{"name":"superstylin","src":"superstylin/superstylin.css"},{"name":"tacit","src":"tacit/tacit.css"},{"name":"vanilla","src":"vanilla/vanilla.css"},{"name":"water","src":"water/water.css"},{"name":"water-dark","src":"water-dark/water-dark.css"},{"name":"writ","src":"writ/writ.css"}]</script>

<style type="text/css" charset="utf-8">
/* cleanrmd overrides */
img { max-width: 100%; }
</style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: auto;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  { color: #00769e; background-color: #f1f3f5; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span { color: #00769e; } /* Normal */
code span.al { color: #ad0000; } /* Alert */
code span.an { color: #5e5e5e; } /* Annotation */
code span.at { color: #657422; } /* Attribute */
code span.bn { color: #ad0000; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #00769e; } /* ControlFlow */
code span.ch { color: #20794d; } /* Char */
code span.cn { color: #8f5902; } /* Constant */
code span.co { color: #5e5e5e; } /* Comment */
code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
code span.dt { color: #ad0000; } /* DataType */
code span.dv { color: #ad0000; } /* DecVal */
code span.er { color: #ad0000; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #ad0000; } /* Float */
code span.fu { color: #4758ab; } /* Function */
code span.im { } /* Import */
code span.in { color: #5e5e5e; } /* Information */
code span.kw { color: #00769e; } /* Keyword */
code span.op { color: #5e5e5e; } /* Operator */
code span.ot { color: #00769e; } /* Other */
code span.pp { color: #ad0000; } /* Preprocessor */
code span.sc { color: #5e5e5e; } /* SpecialChar */
code span.ss { color: #20794d; } /* SpecialString */
code span.st { color: #20794d; } /* String */
code span.va { color: #111111; } /* Variable */
code span.vs { color: #20794d; } /* VerbatimString */
code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
</style>
<script>
// remove everything from pandoc code styles _except_ for 'code span' colors
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      if (/^code span/.test(rule.selectorText)) {
        j++;
        continue;
      }
      sheets[i].deleteRule(j);
    }
  }
})();
</script>

<style>
code, pre { overflow: auto; }
pre code, pre code:not([class]) { white-space: unset; }
</style>


</head>
<body>


<main>
<header>
<h1 id="title" class="toc-ignore">STA 369 Class 02 @ HD &amp; Lecture 03
@ UOA</h1>
<p id="date">2024-07-27</p>
<p id="author">Tianyi He</p>

</header>


<h1 id="lecture-03">Lecture 03</h1>
<h2 id="separate-示例">1. <code>separate()</code> 示例</h2>
<p>我们使用 R 自带的 <code>mtcars</code>
数据集，将汽车品牌和型号分开：</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 加载所需包</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tibble)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 加载mtcars数据集</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(mtcars)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># 假设我们要分离汽车品牌和型号</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># 首先，创建一个包含品牌和型号的字符串列</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>mtcars<span class="sc">$</span>model_str <span class="ot">&lt;-</span> <span class="fu">rownames</span>(mtcars)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># 使用separate()函数分离品牌和型号</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>mtcars_separated <span class="ot">&lt;-</span> <span class="fu">separate</span>(mtcars, model_str, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">&quot;brand&quot;</span>, <span class="st">&quot;model&quot;</span>), <span class="at">sep =</span> <span class="st">&quot; &quot;</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co"># 查看分离后的数据集</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mtcars_separated[, <span class="fu">c</span>(<span class="st">&quot;brand&quot;</span>, <span class="st">&quot;model&quot;</span>)])</span></code></pre></div>
<pre><code>##                     brand      model
## Mazda RX4           Mazda        RX4
## Mazda RX4 Wag       Mazda        RX4
## Datsun 710         Datsun        710
## Hornet 4 Drive     Hornet          4
## Hornet Sportabout  Hornet Sportabout
## Valiant           Valiant       &lt;NA&gt;</code></pre>
<h2 id="mutate-示例">2. <code>mutate()</code> 示例</h2>
<p>我们在 mtcars
数据集中添加一个新的列，计算每辆车的每加仑油耗的燃油效率（mpg）：</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 加载mtcars数据集</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(mtcars)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 使用mutate()函数添加新列 &#39;mpg_efficiency&#39;</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>mtcars_with_mpg <span class="ot">&lt;-</span> <span class="fu">mutate</span>(mtcars, <span class="at">mpg_efficiency =</span> <span class="dv">30</span> <span class="sc">/</span> mpg)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 查看添加新列后的数据集</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mtcars_with_mpg[, <span class="fu">c</span>(<span class="st">&quot;mpg&quot;</span>, <span class="st">&quot;mpg_efficiency&quot;</span>)])</span></code></pre></div>
<pre><code>##                    mpg mpg_efficiency
## Mazda RX4         21.0       1.428571
## Mazda RX4 Wag     21.0       1.428571
## Datsun 710        22.8       1.315789
## Hornet 4 Drive    21.4       1.401869
## Hornet Sportabout 18.7       1.604278
## Valiant           18.1       1.657459</code></pre>
<h2 id="summarise-示例">3. <code>summarise()</code> 示例</h2>
<p>计算 mtcars 数据集中每加仑油耗（mpg）的平均值和标准差：</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 使用summarise()函数计算每加仑油耗的平均值和标准差</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>summary_stats <span class="ot">&lt;-</span> mtcars <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_mpg =</span> <span class="fu">mean</span>(mpg, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_mpg =</span> <span class="fu">sd</span>(mpg, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 查看汇总结果</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>summary_stats</span></code></pre></div>
<pre><code>##    avg_mpg   sd_mpg
## 1 20.09062 6.026948</code></pre>
<h2 id="分组操作-group_by-和-summarise">4. 分组操作
(<code>group_by()</code> 和 <code>summarise()</code>)</h2>
<p>按气缸数分组，并计算每组中每加仑油耗的平均值和标准差：</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 使用group_by()和summarise()进行分组汇总</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>grouped_summary <span class="ot">&lt;-</span> mtcars <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(cyl) <span class="sc">%&gt;%</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_mpg =</span> <span class="fu">mean</span>(mpg, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_mpg =</span> <span class="fu">sd</span>(mpg, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="co"># 查看分组汇总结果</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>grouped_summary</span></code></pre></div>
<pre><code>## # A tibble: 3 × 3
##     cyl avg_mpg sd_mpg
##   &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;
## 1     4    26.7   4.51
## 2     6    19.7   1.45
## 3     8    15.1   2.56</code></pre>
<h2 id="数据连接操作">5. 数据连接操作</h2>
<h3 id="left_join">5.1 <code>left_join()</code></h3>
<p>将保留左侧数据集中的所有行：</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 加载所需包</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tibble)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 创建mtcars_info数据集</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>mtcars_info <span class="ot">&lt;-</span> mtcars <span class="sc">%&gt;%</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rownames_to_column</span>(<span class="at">var =</span> <span class="st">&quot;model&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(model, mpg, cyl, hp)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="co"># 创建mtcars_extra数据集</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>mtcars_extra <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">model =</span> <span class="fu">c</span>(<span class="st">&quot;example 1&quot;</span>, <span class="st">&quot;example 2&quot;</span>, <span class="st">&quot;example 3&quot;</span>, <span class="st">&quot;example 4&quot;</span>, <span class="st">&quot;Mazda RX4&quot;</span>, <span class="st">&quot;Mazda RX4 Wag&quot;</span>, <span class="st">&quot;example 11&quot;</span>, <span class="st">&quot;example 22&quot;</span>, <span class="st">&quot;example 33&quot;</span>, <span class="st">&quot;example 44&quot;</span>, <span class="st">&quot;example 111&quot;</span>, <span class="st">&quot;example 222&quot;</span>, <span class="st">&quot;example 333&quot;</span>, <span class="st">&quot;example 444&quot;</span>, <span class="st">&quot;example 1111&quot;</span>, <span class="st">&quot;example 2222&quot;</span>, <span class="st">&quot;example 3333&quot;</span>, <span class="st">&quot;example 4444&quot;</span>, <span class="st">&quot;example 15&quot;</span>, <span class="st">&quot;example 25&quot;</span>),</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">manufacturer =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">&quot;Ford&quot;</span>, <span class="st">&quot;Chevrolet&quot;</span>), <span class="at">length.out =</span> <span class="dv">20</span>),</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">year =</span> <span class="fu">rep</span>(<span class="dv">2020</span><span class="sc">:</span><span class="dv">2021</span>, <span class="at">length.out =</span> <span class="dv">20</span>)</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a><span class="co"># 使用left_join()连接数据集</span></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>left_join_result <span class="ot">&lt;-</span> <span class="fu">left_join</span>(mtcars_info, mtcars_extra, <span class="at">by =</span> <span class="st">&quot;model&quot;</span>)</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a><span class="co"># 查看结果</span></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>left_join_result</span></code></pre></div>
<pre><code>##                  model  mpg cyl  hp manufacturer year
## 1            Mazda RX4 21.0   6 110         Ford 2020
## 2        Mazda RX4 Wag 21.0   6 110    Chevrolet 2021
## 3           Datsun 710 22.8   4  93         &lt;NA&gt;   NA
## 4       Hornet 4 Drive 21.4   6 110         &lt;NA&gt;   NA
## 5    Hornet Sportabout 18.7   8 175         &lt;NA&gt;   NA
## 6              Valiant 18.1   6 105         &lt;NA&gt;   NA
## 7           Duster 360 14.3   8 245         &lt;NA&gt;   NA
## 8            Merc 240D 24.4   4  62         &lt;NA&gt;   NA
## 9             Merc 230 22.8   4  95         &lt;NA&gt;   NA
## 10            Merc 280 19.2   6 123         &lt;NA&gt;   NA
## 11           Merc 280C 17.8   6 123         &lt;NA&gt;   NA
## 12          Merc 450SE 16.4   8 180         &lt;NA&gt;   NA
## 13          Merc 450SL 17.3   8 180         &lt;NA&gt;   NA
## 14         Merc 450SLC 15.2   8 180         &lt;NA&gt;   NA
## 15  Cadillac Fleetwood 10.4   8 205         &lt;NA&gt;   NA
## 16 Lincoln Continental 10.4   8 215         &lt;NA&gt;   NA
## 17   Chrysler Imperial 14.7   8 230         &lt;NA&gt;   NA
## 18            Fiat 128 32.4   4  66         &lt;NA&gt;   NA
## 19         Honda Civic 30.4   4  52         &lt;NA&gt;   NA
## 20      Toyota Corolla 33.9   4  65         &lt;NA&gt;   NA
## 21       Toyota Corona 21.5   4  97         &lt;NA&gt;   NA
## 22    Dodge Challenger 15.5   8 150         &lt;NA&gt;   NA
## 23         AMC Javelin 15.2   8 150         &lt;NA&gt;   NA
## 24          Camaro Z28 13.3   8 245         &lt;NA&gt;   NA
## 25    Pontiac Firebird 19.2   8 175         &lt;NA&gt;   NA
## 26           Fiat X1-9 27.3   4  66         &lt;NA&gt;   NA
## 27       Porsche 914-2 26.0   4  91         &lt;NA&gt;   NA
## 28        Lotus Europa 30.4   4 113         &lt;NA&gt;   NA
## 29      Ford Pantera L 15.8   8 264         &lt;NA&gt;   NA
## 30        Ferrari Dino 19.7   6 175         &lt;NA&gt;   NA
## 31       Maserati Bora 15.0   8 335         &lt;NA&gt;   NA
## 32          Volvo 142E 21.4   4 109         &lt;NA&gt;   NA</code></pre>
<h3 id="right_join">5.2 <code>right_join()</code></h3>
<p>将保留右侧数据集中的所有行：</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 使用right_join()连接数据集</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>right_join_result <span class="ot">&lt;-</span> <span class="fu">right_join</span>(mtcars_info, mtcars_extra, <span class="at">by =</span> <span class="st">&quot;model&quot;</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 查看结果</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>right_join_result</span></code></pre></div>
<pre><code>##            model mpg cyl  hp manufacturer year
## 1      Mazda RX4  21   6 110         Ford 2020
## 2  Mazda RX4 Wag  21   6 110    Chevrolet 2021
## 3      example 1  NA  NA  NA         Ford 2020
## 4      example 2  NA  NA  NA    Chevrolet 2021
## 5      example 3  NA  NA  NA         Ford 2020
## 6      example 4  NA  NA  NA    Chevrolet 2021
## 7     example 11  NA  NA  NA         Ford 2020
## 8     example 22  NA  NA  NA    Chevrolet 2021
## 9     example 33  NA  NA  NA         Ford 2020
## 10    example 44  NA  NA  NA    Chevrolet 2021
## 11   example 111  NA  NA  NA         Ford 2020
## 12   example 222  NA  NA  NA    Chevrolet 2021
## 13   example 333  NA  NA  NA         Ford 2020
## 14   example 444  NA  NA  NA    Chevrolet 2021
## 15  example 1111  NA  NA  NA         Ford 2020
## 16  example 2222  NA  NA  NA    Chevrolet 2021
## 17  example 3333  NA  NA  NA         Ford 2020
## 18  example 4444  NA  NA  NA    Chevrolet 2021
## 19    example 15  NA  NA  NA         Ford 2020
## 20    example 25  NA  NA  NA    Chevrolet 2021</code></pre>
<h3 id="full_join">5.3 <code>full_join()</code></h3>
<p>将保留两个数据集中的所有行：</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 使用full_join()连接数据集</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>full_join_result <span class="ot">&lt;-</span> <span class="fu">full_join</span>(mtcars_info, mtcars_extra, <span class="at">by =</span> <span class="st">&quot;model&quot;</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 查看结果</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>full_join_result</span></code></pre></div>
<pre><code>##                  model  mpg cyl  hp manufacturer year
## 1            Mazda RX4 21.0   6 110         Ford 2020
## 2        Mazda RX4 Wag 21.0   6 110    Chevrolet 2021
## 3           Datsun 710 22.8   4  93         &lt;NA&gt;   NA
## 4       Hornet 4 Drive 21.4   6 110         &lt;NA&gt;   NA
## 5    Hornet Sportabout 18.7   8 175         &lt;NA&gt;   NA
## 6              Valiant 18.1   6 105         &lt;NA&gt;   NA
## 7           Duster 360 14.3   8 245         &lt;NA&gt;   NA
## 8            Merc 240D 24.4   4  62         &lt;NA&gt;   NA
## 9             Merc 230 22.8   4  95         &lt;NA&gt;   NA
## 10            Merc 280 19.2   6 123         &lt;NA&gt;   NA
## 11           Merc 280C 17.8   6 123         &lt;NA&gt;   NA
## 12          Merc 450SE 16.4   8 180         &lt;NA&gt;   NA
## 13          Merc 450SL 17.3   8 180         &lt;NA&gt;   NA
## 14         Merc 450SLC 15.2   8 180         &lt;NA&gt;   NA
## 15  Cadillac Fleetwood 10.4   8 205         &lt;NA&gt;   NA
## 16 Lincoln Continental 10.4   8 215         &lt;NA&gt;   NA
## 17   Chrysler Imperial 14.7   8 230         &lt;NA&gt;   NA
## 18            Fiat 128 32.4   4  66         &lt;NA&gt;   NA
## 19         Honda Civic 30.4   4  52         &lt;NA&gt;   NA
## 20      Toyota Corolla 33.9   4  65         &lt;NA&gt;   NA
## 21       Toyota Corona 21.5   4  97         &lt;NA&gt;   NA
## 22    Dodge Challenger 15.5   8 150         &lt;NA&gt;   NA
## 23         AMC Javelin 15.2   8 150         &lt;NA&gt;   NA
## 24          Camaro Z28 13.3   8 245         &lt;NA&gt;   NA
## 25    Pontiac Firebird 19.2   8 175         &lt;NA&gt;   NA
## 26           Fiat X1-9 27.3   4  66         &lt;NA&gt;   NA
## 27       Porsche 914-2 26.0   4  91         &lt;NA&gt;   NA
## 28        Lotus Europa 30.4   4 113         &lt;NA&gt;   NA
## 29      Ford Pantera L 15.8   8 264         &lt;NA&gt;   NA
## 30        Ferrari Dino 19.7   6 175         &lt;NA&gt;   NA
## 31       Maserati Bora 15.0   8 335         &lt;NA&gt;   NA
## 32          Volvo 142E 21.4   4 109         &lt;NA&gt;   NA
## 33           example 1   NA  NA  NA         Ford 2020
## 34           example 2   NA  NA  NA    Chevrolet 2021
## 35           example 3   NA  NA  NA         Ford 2020
## 36           example 4   NA  NA  NA    Chevrolet 2021
## 37          example 11   NA  NA  NA         Ford 2020
## 38          example 22   NA  NA  NA    Chevrolet 2021
## 39          example 33   NA  NA  NA         Ford 2020
## 40          example 44   NA  NA  NA    Chevrolet 2021
## 41         example 111   NA  NA  NA         Ford 2020
## 42         example 222   NA  NA  NA    Chevrolet 2021
## 43         example 333   NA  NA  NA         Ford 2020
## 44         example 444   NA  NA  NA    Chevrolet 2021
## 45        example 1111   NA  NA  NA         Ford 2020
## 46        example 2222   NA  NA  NA    Chevrolet 2021
## 47        example 3333   NA  NA  NA         Ford 2020
## 48        example 4444   NA  NA  NA    Chevrolet 2021
## 49          example 15   NA  NA  NA         Ford 2020
## 50          example 25   NA  NA  NA    Chevrolet 2021</code></pre>
<h3 id="inner_join">5.4 <code>inner_join()</code></h3>
<p>仅保留两个数据集中的匹配行：</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 使用inner_join()连接数据集</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>inner_join_result <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(mtcars_info, mtcars_extra, <span class="at">by =</span> <span class="st">&quot;model&quot;</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 查看结果</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>inner_join_result</span></code></pre></div>
<pre><code>##           model mpg cyl  hp manufacturer year
## 1     Mazda RX4  21   6 110         Ford 2020
## 2 Mazda RX4 Wag  21   6 110    Chevrolet 2021</code></pre>
<h1 id="lecture-04">Lecture 04</h1>
<h2 id="数据生成">1. 数据生成</h2>
<p>我们首先生成一组模拟数据，这些数据遵循简单线性关系：</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 加载所需包</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 设置随机种子以确保结果可重复</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 生成模拟数据</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>beta0 <span class="ot">&lt;-</span> <span class="dv">5</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>beta1 <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>epsilon <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">3</span>)</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> beta0 <span class="sc">+</span> beta1 <span class="sc">*</span> x <span class="sc">+</span> epsilon</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a><span class="co"># 创建数据框</span></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> x, <span class="at">y =</span> y)</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a><span class="co"># 查看前几行数据</span></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code></pre></div>
<pre><code>##          x         y
## 1 44.39524  91.65927
## 2 47.69823 101.16710
## 3 65.58708 135.43409
## 4 50.70508 105.36754
## 5 51.29288 104.73090
## 6 67.15065 139.16622</code></pre>
<h2 id="拟合线性回归模型">2. 拟合线性回归模型</h2>
<p>我们使用 lm() 函数来拟合简单线性回归模型：</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 拟合线性回归模型</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> data)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 查看模型摘要</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x, data = data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.7220 -2.0505 -0.2625  1.7419  9.8712 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  5.47867    1.65794   3.304  0.00133 ** 
## x            1.98426    0.03206  61.885  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.912 on 98 degrees of freedom
## Multiple R-squared:  0.975,  Adjusted R-squared:  0.9748 
## F-statistic:  3830 on 1 and 98 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>得出的结论：</p>
<ul>
<li>Since the p-value of <code>2e-16 &lt; 0.05</code>, we have enough
evidence to conclude that x is significant.</li>
<li><code>97.48%</code> of y can be explained by <code>x</code>.</li>
<li>For every unit increased in <code>x</code>, <code>y</code> will be
increased by <code>1.98426</code> unit.</li>
<li>The equation of the model can be written by
<code>y = 5.47867 + 1.98426 * x</code>.</li>
</ul>
<h2 id="预测和结果可视化">3. 预测和结果可视化</h2>
<p>我们可以使用拟合的模型进行预测，并将结果可视化：</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 预测值</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>predicted_y <span class="ot">&lt;-</span> <span class="fu">predict</span>(model, <span class="at">newdata =</span> data)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 绘制数据和拟合线</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y)) <span class="sc">+</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="fu">aes</span>(<span class="at">y =</span> predicted_y), <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;简单线性回归模型&quot;</span>,</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;自变量 x&quot;</span>,</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;因变量 y&quot;</span>) <span class="sc">+</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="class02_modified_files/figure-html5/unnamed-chunk-9-1.png" width="960" /></p>
<h4 id="rss">RSS</h4>
<p>每一个蓝点到红线之间的距离的平方，全部相加，得到的就是<code>RSS</code>.</p>
<h5 id="为什么要加这个平方">为什么要加这个平方？</h5>
<ul>
<li>放大误差：使得模型对大的误差更加敏感</li>
<li>避免负值：避免因为正负值互相抵消而被忽略的拟合好坏</li>
</ul>
<p>记一下三个公式：</p>
<p><span class="math display">\[RSS = \sum_{i} (y_i -
\hat{y}_i)^2\]</span> <span class="math display">\[TSS = \sum_{i} (y_i -
\bar{y}_i)^2\]</span> <span class="math display">\[R^2 = \frac{TSS -
RSS}{TSS} = 1 - \frac{RSS}{TSS}\]</span></p>
<ul>
<li><p>The observations are independent.</p></li>
<li><p>The <strong>true</strong> relationship between <span
class="math inline">\(X\)</span> and <span
class="math inline">\(Y\)</span> is linear.</p></li>
<li><p>For the error term is normally distributed and of a constant
variance, i.e. <span class="math inline">\(Y = X \beta +
\epsilon\)</span>, <span class="math inline">\(\epsilon \sim
\text{Normal}(\mu, \sigma)\)</span>.</p>
<ul>
<li><p>Errors are independent.</p></li>
<li><p>Errors are independent with <span
class="math inline">\(X\)</span>.</p></li>
<li><p>Errors are normally distributed.</p></li>
<li><p>Homoscedasticity of errors (equal-variance).</p></li>
</ul></li>
</ul>
<h2 id="模型诊断">4. 模型诊断</h2>
<p>检查模型的诊断信息，包括残差和拟合值：</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 绘制残差图</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model)</span></code></pre></div>
<p><img src="class02_modified_files/figure-html5/unnamed-chunk-10-1.png" width="960" /></p>
<h2 id="transformation-interaction">Transformation &amp;
Interaction</h2>
<h3 id="数据生成-1">1. 数据生成</h3>
<p>我们首先生成一组模拟数据，并添加一个交互作用项：</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 加载所需包</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 设置随机种子以确保结果可重复</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 生成模拟数据</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">30</span>, <span class="at">sd =</span> <span class="dv">5</span>)</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>beta0 <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>beta1 <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>beta2 <span class="ot">&lt;-</span> <span class="dv">3</span></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>beta12 <span class="ot">&lt;-</span> <span class="fl">1.5</span></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>epsilon <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">5</span>)</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> beta0 <span class="sc">+</span> beta1 <span class="sc">*</span> x1 <span class="sc">+</span> beta2 <span class="sc">*</span> x2 <span class="sc">+</span> beta12 <span class="sc">*</span> x1 <span class="sc">*</span> x2 <span class="sc">+</span> epsilon</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a><span class="co"># 创建数据框</span></span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x1 =</span> x1, <span class="at">x2 =</span> x2, <span class="at">y =</span> y)</span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a><span class="co"># 查看前几行数据</span></span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code></pre></div>
<pre><code>##         x1       x2        y
## 1 44.39524 26.44797 1950.374
## 2 47.69823 31.28442 2444.129
## 3 65.58708 28.76654 3056.218
## 4 50.70508 28.26229 2348.475
## 5 51.29288 25.24191 2128.335
## 6 67.15065 29.77486 3230.347</code></pre>
<h3 id="数据变换">2. 数据变换</h3>
<p>我们对 <code>x1</code> 和 <code>y</code>
进行对数变换，观察变换对模型的影响：</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 对数变换</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>log_x1 <span class="ot">&lt;-</span> <span class="fu">log</span>(data<span class="sc">$</span>x1 <span class="sc">+</span> <span class="dv">1</span>) <span class="co"># +1 避免对数计算中的负值</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>log_y <span class="ot">&lt;-</span> <span class="fu">log</span>(data<span class="sc">$</span>y <span class="sc">+</span> <span class="dv">1</span>)   <span class="co"># +1 避免对数计算中的负值</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 拟合变换后的线性回归模型</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>model_transformed <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_y <span class="sc">~</span> log_x1 <span class="sc">+</span> x2, <span class="at">data =</span> data)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 查看模型摘要</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_transformed)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = log_y ~ log_x1 + x2, data = data)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.081558 -0.004407  0.006573  0.010765  0.020685 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 2.9936402  0.0388797   77.00   &lt;2e-16 ***
## log_x1      0.9796682  0.0094167  104.03   &lt;2e-16 ***
## x2          0.0315778  0.0003545   89.06   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.01705 on 97 degrees of freedom
## Multiple R-squared:  0.9947, Adjusted R-squared:  0.9946 
## F-statistic:  9059 on 2 and 97 DF,  p-value: &lt; 2.2e-16</code></pre>
<h3 id="交互作用">3. 交互作用</h3>
<p>我们将拟合一个包含 <code>x1</code> 和 <code>x2</code>
交互作用项的线性回归模型：</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 拟合包含交互作用项的线性回归模型</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>model_interaction <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">*</span> x2, <span class="at">data =</span> data)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 查看模型摘要</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_interaction)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x1 * x2, data = data)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -9.360 -3.389 -0.543  2.949 11.583 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 35.86089   16.74106   2.142 0.034716 *  
## x1           1.47627    0.33307   4.432 2.48e-05 ***
## x2           2.23881    0.57341   3.904 0.000176 ***
## x1:x2        1.51591    0.01145 132.402  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.734 on 96 degrees of freedom
## Multiple R-squared:  0.9999, Adjusted R-squared:  0.9999 
## F-statistic: 4.366e+05 on 3 and 96 DF,  p-value: &lt; 2.2e-16</code></pre>
<h3 id="结果可视化">4. 结果可视化</h3>
<h4 id="数据变换后的结果可视化">4.1 数据变换后的结果可视化</h4>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 绘制原始数据</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> x1, <span class="at">y =</span> y)) <span class="sc">+</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;原始数据&quot;</span>,</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;自变量 x1&quot;</span>,</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;因变量 y&quot;</span>) <span class="sc">+</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="co"># 绘制对数变换后的数据</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> log_x1, <span class="at">y =</span> log_y)) <span class="sc">+</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;对数变换后的数据&quot;</span>,</span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;对数变换后的 x1&quot;</span>,</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;对数变换后的 y&quot;</span>) <span class="sc">+</span></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a><span class="co"># 显示图形</span></span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p1, p2, <span class="at">nrow =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="class02_modified_files/figure-html5/unnamed-chunk-13-1.png" width="960" /></p>
<h4 id="交互作用项的可视化">4.2 交互作用项的可视化</h4>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 绘制包含交互作用的模型预测</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>predicted_y <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_interaction, <span class="at">newdata =</span> data)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 生成交互作用效果图</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> x1, <span class="at">y =</span> predicted_y, <span class="at">color =</span> <span class="fu">factor</span>(x2))) <span class="sc">+</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group =</span> x2), <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;交互作用模型的预测结果&quot;</span>,</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;自变量 x1&quot;</span>,</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;预测的 y&quot;</span>,</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">&quot;自变量 x2&quot;</span>) <span class="sc">+</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>)</span></code></pre></div>
<p><img src="class02_modified_files/figure-html5/unnamed-chunk-14-1.png" width="960" /></p>
<h4 id="数据变换的意义">数据变换的意义</h4>
<h5 id="对数变换log-transformation"><strong>对数变换（Log
Transformation）</strong>：</h5>
<ul>
<li><strong>目的</strong>：对数变换通常用于处理数据中的非线性关系或异方差性（即方差不恒定）。它可以使数据分布更加接近正态分布，从而使模型假设更符合实际情况。</li>
<li><strong>效果</strong>：对数变换可以使得数据中的极端值影响减小，帮助改善模型的拟合效果和解释能力。</li>
</ul>
<h4 id="交互作用的意义">交互作用的意义</h4>
<h5
id="交互作用interaction"><strong>交互作用（Interaction）</strong>：</h5>
<ul>
<li><strong>目的</strong>：交互作用项用于表示自变量之间的相互影响。简单来说，如果一个自变量对因变量的影响依赖于另一个自变量的水平，那么这两个自变量之间存在交互作用。</li>
<li><strong>效果</strong>：引入交互作用项可以帮助捕捉这种复杂关系，从而使模型对数据的拟合更加准确。</li>
</ul>
<h2 id="bootstrap">Bootstrap</h2>
<h3 id="数据生成-2">1. 数据生成</h3>
<p>我们生成一组模拟数据：</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 加载所需包</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 设置随机种子以确保结果可重复</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 生成模拟数据</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>beta0 <span class="ot">&lt;-</span> <span class="dv">5</span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>beta1 <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>epsilon <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">3</span>)</span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> beta0 <span class="sc">+</span> beta1 <span class="sc">*</span> x <span class="sc">+</span> epsilon</span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a><span class="co"># 创建数据框</span></span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> x, <span class="at">y =</span> y)</span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a><span class="co"># 查看前几行数据</span></span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code></pre></div>
<pre><code>##          x         y
## 1 44.39524  91.65927
## 2 47.69823 101.16710
## 3 65.58708 135.43409
## 4 50.70508 105.36754
## 5 51.29288 104.73090
## 6 67.15065 139.16622</code></pre>
<h3 id="bootstrap-方法">2. Bootstrap 方法</h3>
<p>我们使用 Bootstrap 方法来估计线性回归模型参数的标准误差：</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 加载所需包</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(boot)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 定义回归模型函数</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>boot_fn <span class="ot">&lt;-</span> <span class="cf">function</span>(data, indices) {</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  d <span class="ot">&lt;-</span> data[indices, ]  <span class="co"># 重新抽样</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> d)</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">coef</span>(fit))</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a><span class="co"># 进行Bootstrap抽样</span></span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>bootstrap_results <span class="ot">&lt;-</span> <span class="fu">boot</span>(data, <span class="at">statistic =</span> boot_fn, <span class="at">R =</span> <span class="dv">1000</span>)</span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a><span class="co"># 查看Bootstrap结果</span></span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(bootstrap_results)</span></code></pre></div>
<pre><code>## 
## ORDINARY NONPARAMETRIC BOOTSTRAP
## 
## 
## Call:
## boot(data = data, statistic = boot_fn, R = 1000)
## 
## 
## Bootstrap Statistics :
##     original       bias    std. error
## t1* 5.478665  0.039044917  1.68026627
## t2* 1.984259 -0.000669357  0.03151438</code></pre>
<h3 id="sandwich-方法">3. Sandwich 方法</h3>
<p>我们使用 Sandwich 方法来计算稳健标准误差：</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 加载所需包</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sandwich)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 拟合线性回归模型</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> data)</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 计算稳健标准误差</span></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>robust_se <span class="ot">&lt;-</span> <span class="fu">coeftest</span>(model, <span class="at">vcov =</span> <span class="fu">vcovHC</span>(model, <span class="at">type =</span> <span class="st">&quot;HC1&quot;</span>))</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a><span class="co"># 查看结果</span></span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(robust_se)</span></code></pre></div>
<pre><code>## 
## t test of coefficients:
## 
##             Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept) 5.478665   1.670626  3.2794  0.001441 ** 
## x           1.984259   0.031282 63.4316 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<h3 id="结果解释">4. 结果解释</h3>
<p>我们可以将标准回归结果与稳健标准误差进行对比：</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 标准回归结果</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)<span class="sc">$</span>coefficients</span></code></pre></div>
<pre><code>##             Estimate Std. Error   t value     Pr(&gt;|t|)
## (Intercept) 5.478665 1.65794262  3.304496 1.329703e-03
## x           1.984259 0.03206358 61.885111 2.330948e-80</code></pre>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bootstrap结果</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>bootstrap_results</span></code></pre></div>
<pre><code>## 
## ORDINARY NONPARAMETRIC BOOTSTRAP
## 
## 
## Call:
## boot(data = data, statistic = boot_fn, R = 1000)
## 
## 
## Bootstrap Statistics :
##     original       bias    std. error
## t1* 5.478665  0.039044917  1.68026627
## t2* 1.984259 -0.000669357  0.03151438</code></pre>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sandwich结果</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>robust_se</span></code></pre></div>
<pre><code>## 
## t test of coefficients:
## 
##             Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept) 5.478665   1.670626  3.2794  0.001441 ** 
## x           1.984259   0.031282 63.4316 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>

</main>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
document.addEventListener("DOMContentLoaded", function(event) {
  var script = document.createElement("script");
  script.type = "text/javascript";
  script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
  document.getElementsByTagName("head")[0].appendChild(script);
});
</script>

</body>
</html>
